package kz.qwertukg.generator

import org.atteo.evo.inflector.English
import com.google.common.base.CaseFormat
import java.io.File

/**
 * Created by Daniil Rakhmatulin.
 */
val String.snake: String get() = CaseFormat.LOWER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, this)
val String.camel: String get() = CaseFormat.LOWER_UNDERSCORE.to(CaseFormat.LOWER_CAMEL, this)
val String.route: String get() = CaseFormat.LOWER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, this).replace("_", "-")

val String.plural: String get() = English.plural(this)
val String.singular: String get() = English.plural(this, 1)

val String.toPath: String get() = replace(".", File.separator)

val logo: String get() = StringBuilder().apply {
    appendln("********************************************************")
    appendln("* Kotlin Spring Rest Api Basic Code Generator          *")
    appendln("* Author: Daniil Rakhmatulin                           *")
    appendln("* GitHub: https://github.com/qwertukg/spring-generator *")
    appendln("* Licence: Do any what you want                        *")
    appendln("********************************************************")
}.toString()

val watermark: String get() = StringBuilder().apply {
    appendln("/**")
    appendln(" * Generated by: Kotlin Spring Rest Api Basic Code Generator")
    appendln(" * Author: Daniil Rakhmatulin")
    appendln(" * GitHub: https://github.com/qwertukg/spring-generator")
    appendln(" * Licence: Do any what you want")
    appendln(" */")
}.toString()